Repository KamandPrompt/kamandprompt.github.io, pull requests merged in 2018-06, with the labels that each got.

#18 This commit modifies the footer
  css/styles.css
  index.html
Labels: process/pending_review, size/XS

#21 GSoC page
  css/gsoc.css
  gsoc/css/animate-custom.css
  gsoc/css/bootstrap.css
  gsoc/css/icomoon.css
  gsoc/css/icomoon/icomoon-.eot
  gsoc/css/icomoon/icomoon.eot
  gsoc/css/icomoon/icomoon.svg
  gsoc/css/icomoon/icomoon.ttf
  gsoc/css/icomoon/icomoon.woff
  gsoc/css/main.css
  gsoc/img/bg.jpg
  gsoc/img/people/abhigyankhaund.jpg
  gsoc/img/people/abhijeetsharma.jpg
  gsoc/img/people/akashsharma.jpg
  gsoc/img/people/akshgautam.jpeg
  gsoc/img/people/ayushyadav.jpg
  gsoc/img/people/chiragvashist.jpg
  gsoc/img/people/lakshayarora.jpg
  gsoc/img/people/mukarramtailor.jpg
  gsoc/img/people/pinanksolanki.jpg
  gsoc/img/people/priyanshukhandelwal.jpg
  gsoc/img/people/sagargupta.jpg
  gsoc/img/people/sahilarora.jpg
  gsoc/img/people/sahilyadav.jpg
  gsoc/img/people/samriddhijain.jpg
  gsoc/img/people/swapnilsharma1.jpg
  gsoc/img/people/swapnilsharma2.jpg
  gsoc/index.html
  gsoc/js/bootstrap.js
  gsoc/js/bootstrap.min.js
  gsoc/js/interact.js
  gsoc/js/jquery-func.js
  gsoc/js/jquery.easing.1.3.js
  gsoc/js/jquery.min.js
  gsoc/js/modernizr.custom.js
  gsoc/js/retina.js
  gsoc/js/smoothscroll.js
  index.html
Labels: process/pending_review, size/XXL

#23 Added About Section
  css/styles.css
  index.html
Labels: enhancement

#25 Added Smooth Scrolling for all Links
  js/script.js
Labels: enhancement
