Repository KamandPrompt/kamandprompt.github.io, pull requests merged in 2020-10, with the labels that each got.

#115 New section
  gsoc/img/people/dipanshuverma.jpg
  gsoc/img/people/jahnvigupta.jpg
  gsoc/img/people/nidhijain.jpg
  gsoc/index.html
Labels: size: L

#120 Improved way to add copyrigh year
  gsoc/index.html
  hack36/index.html
  hof/index.html
  icpc/index.html
  js/script.js
  project_contributors/index.html
Labels: size: M

#118 improved project_contributors page
  project_contributors/css/styles.css
  project_contributors/img/bg.jpg
  project_contributors/index.html
  project_contributors/js/script.js
Labels: size: XL

#119 Made the GSOC selections collapsible and some minor adjustment of button responsiveness
  css/styles.css
  gsoc/css/main.css
  gsoc/index.html
  gsoc/js/foldable.js
Labels: hacktoberfest-accepted, size: XL

#122 fixed the href attr for the logo link
  project_contributors/index.html
Labels: size: XS

#123 Bug fix: copyright not updating on home page
  index.html
Labels: size: XS
